// Generated by gencpp from file openpose_ros_msgs/Persons.msg
// DO NOT EDIT!


#ifndef OPENPOSE_ROS_MSGS_MESSAGE_PERSONS_H
#define OPENPOSE_ROS_MSGS_MESSAGE_PERSONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <openpose_ros_msgs/PersonDetection.h>

namespace openpose_ros_msgs
{
template <class ContainerAllocator>
struct Persons_
{
  typedef Persons_<ContainerAllocator> Type;

  Persons_()
    : persons()
    , rostime()
    , image_w(0)
    , image_h(0)  {
    }
  Persons_(const ContainerAllocator& _alloc)
    : persons(_alloc)
    , rostime()
    , image_w(0)
    , image_h(0)  {
  (void)_alloc;
    }



   typedef std::vector< ::openpose_ros_msgs::PersonDetection_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::openpose_ros_msgs::PersonDetection_<ContainerAllocator> >::other >  _persons_type;
  _persons_type persons;

   typedef ros::Time _rostime_type;
  _rostime_type rostime;

   typedef uint32_t _image_w_type;
  _image_w_type image_w;

   typedef uint32_t _image_h_type;
  _image_h_type image_h;





  typedef boost::shared_ptr< ::openpose_ros_msgs::Persons_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpose_ros_msgs::Persons_<ContainerAllocator> const> ConstPtr;

}; // struct Persons_

typedef ::openpose_ros_msgs::Persons_<std::allocator<void> > Persons;

typedef boost::shared_ptr< ::openpose_ros_msgs::Persons > PersonsPtr;
typedef boost::shared_ptr< ::openpose_ros_msgs::Persons const> PersonsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpose_ros_msgs::Persons_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpose_ros_msgs::Persons_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace openpose_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'openpose_ros_msgs': ['/home/zheng/robot_ws_zheng/src/ros-openpose/openpose_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::openpose_ros_msgs::Persons_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpose_ros_msgs::Persons_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpose_ros_msgs::Persons_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpose_ros_msgs::Persons_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpose_ros_msgs::Persons_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpose_ros_msgs::Persons_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpose_ros_msgs::Persons_<ContainerAllocator> >
{
  static const char* value()
  {
    return "364e552085331e28feea9ffef91f2929";
  }

  static const char* value(const ::openpose_ros_msgs::Persons_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x364e552085331e28ULL;
  static const uint64_t static_value2 = 0xfeea9ffef91f2929ULL;
};

template<class ContainerAllocator>
struct DataType< ::openpose_ros_msgs::Persons_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpose_ros_msgs/Persons";
  }

  static const char* value(const ::openpose_ros_msgs::Persons_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpose_ros_msgs::Persons_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PersonDetection[] persons\n"
"time rostime\n"
"uint32 image_w\n"
"uint32 image_h\n"
"\n"
"================================================================================\n"
"MSG: openpose_ros_msgs/PersonDetection\n"
"BodyPartDetection[] face_landmark\n"
"BodyPartDetection[] body_part\n"
"\n"
"================================================================================\n"
"MSG: openpose_ros_msgs/BodyPartDetection\n"
"uint32 part_id\n"
"uint32 x\n"
"uint32 y\n"
"float32 confidence\n"
;
  }

  static const char* value(const ::openpose_ros_msgs::Persons_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpose_ros_msgs::Persons_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.persons);
      stream.next(m.rostime);
      stream.next(m.image_w);
      stream.next(m.image_h);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Persons_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpose_ros_msgs::Persons_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openpose_ros_msgs::Persons_<ContainerAllocator>& v)
  {
    s << indent << "persons[]" << std::endl;
    for (size_t i = 0; i < v.persons.size(); ++i)
    {
      s << indent << "  persons[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::openpose_ros_msgs::PersonDetection_<ContainerAllocator> >::stream(s, indent + "    ", v.persons[i]);
    }
    s << indent << "rostime: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.rostime);
    s << indent << "image_w: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.image_w);
    s << indent << "image_h: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.image_h);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENPOSE_ROS_MSGS_MESSAGE_PERSONS_H
