(cl:defpackage human_moveit_config-srv
  (:use )
  (:export
   "GETHUMANIK"
   "<GETHUMANIK-REQUEST>"
   "GETHUMANIK-REQUEST"
   "<GETHUMANIK-RESPONSE>"
   "GETHUMANIK-RESPONSE"
   "GETJACOBIAN"
   "<GETJACOBIAN-REQUEST>"
   "GETJACOBIAN-REQUEST"
   "<GETJACOBIAN-RESPONSE>"
   "GETJACOBIAN-RESPONSE"
  ))

