set(_CATKIN_CURRENT_PACKAGE "lpsolve_catkin")
set(lpsolve_catkin_VERSION "5.5.2")
set(lpsolve_catkin_MAINTAINER "Simon Lynen <slynen@ethz.ch>")
set(lpsolve_catkin_PACKAGE_FORMAT "1")
set(lpsolve_catkin_BUILD_DEPENDS )
set(lpsolve_catkin_BUILD_EXPORT_DEPENDS )
set(lpsolve_catkin_BUILDTOOL_DEPENDS "catkin" "catkin_simple")
set(lpsolve_catkin_BUILDTOOL_EXPORT_DEPENDS )
set(lpsolve_catkin_EXEC_DEPENDS )
set(lpsolve_catkin_RUN_DEPENDS )
set(lpsolve_catkin_TEST_DEPENDS )
set(lpsolve_catkin_DOC_DEPENDS )
set(lpsolve_catkin_URL_WEBSITE "")
set(lpsolve_catkin_URL_BUGTRACKER "")
set(lpsolve_catkin_URL_REPOSITORY "")
set(lpsolve_catkin_DEPRECATED "")