// Generated by gencpp from file openpose_ros_msgs/PointWithProb.msg
// DO NOT EDIT!


#ifndef OPENPOSE_ROS_MSGS_MESSAGE_POINTWITHPROB_H
#define OPENPOSE_ROS_MSGS_MESSAGE_POINTWITHPROB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openpose_ros_msgs
{
template <class ContainerAllocator>
struct PointWithProb_
{
  typedef PointWithProb_<ContainerAllocator> Type;

  PointWithProb_()
    : x(0.0)
    , y(0.0)
    , prob(0.0)  {
    }
  PointWithProb_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , prob(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _prob_type;
  _prob_type prob;





  typedef boost::shared_ptr< ::openpose_ros_msgs::PointWithProb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpose_ros_msgs::PointWithProb_<ContainerAllocator> const> ConstPtr;

}; // struct PointWithProb_

typedef ::openpose_ros_msgs::PointWithProb_<std::allocator<void> > PointWithProb;

typedef boost::shared_ptr< ::openpose_ros_msgs::PointWithProb > PointWithProbPtr;
typedef boost::shared_ptr< ::openpose_ros_msgs::PointWithProb const> PointWithProbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpose_ros_msgs::PointWithProb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpose_ros_msgs::PointWithProb_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace openpose_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'openpose_ros_msgs': ['/home/zheng/robot_ws_zheng/src/openpose_ros/openpose_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::openpose_ros_msgs::PointWithProb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpose_ros_msgs::PointWithProb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpose_ros_msgs::PointWithProb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpose_ros_msgs::PointWithProb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpose_ros_msgs::PointWithProb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpose_ros_msgs::PointWithProb_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpose_ros_msgs::PointWithProb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9aa8eca031892a98235f2ba7dab5caf";
  }

  static const char* value(const ::openpose_ros_msgs::PointWithProb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9aa8eca031892a9ULL;
  static const uint64_t static_value2 = 0x8235f2ba7dab5cafULL;
};

template<class ContainerAllocator>
struct DataType< ::openpose_ros_msgs::PointWithProb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpose_ros_msgs/PointWithProb";
  }

  static const char* value(const ::openpose_ros_msgs::PointWithProb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpose_ros_msgs::PointWithProb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 prob\n"
;
  }

  static const char* value(const ::openpose_ros_msgs::PointWithProb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpose_ros_msgs::PointWithProb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.prob);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointWithProb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpose_ros_msgs::PointWithProb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openpose_ros_msgs::PointWithProb_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "prob: ";
    Printer<double>::stream(s, indent + "  ", v.prob);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENPOSE_ROS_MSGS_MESSAGE_POINTWITHPROB_H
