// Generated by gencpp from file openni2_tracker/TrackerUserArray.msg
// DO NOT EDIT!


#ifndef OPENNI2_TRACKER_MESSAGE_TRACKERUSERARRAY_H
#define OPENNI2_TRACKER_MESSAGE_TRACKERUSERARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <openni2_tracker/TrackerUser.h>

namespace openni2_tracker
{
template <class ContainerAllocator>
struct TrackerUserArray_
{
  typedef TrackerUserArray_<ContainerAllocator> Type;

  TrackerUserArray_()
    : users()
    , numUsers(0)  {
    }
  TrackerUserArray_(const ContainerAllocator& _alloc)
    : users(_alloc)
    , numUsers(0)  {
  (void)_alloc;
    }



   typedef std::vector< ::openni2_tracker::TrackerUser_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::openni2_tracker::TrackerUser_<ContainerAllocator> >::other >  _users_type;
  _users_type users;

   typedef int8_t _numUsers_type;
  _numUsers_type numUsers;





  typedef boost::shared_ptr< ::openni2_tracker::TrackerUserArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openni2_tracker::TrackerUserArray_<ContainerAllocator> const> ConstPtr;

}; // struct TrackerUserArray_

typedef ::openni2_tracker::TrackerUserArray_<std::allocator<void> > TrackerUserArray;

typedef boost::shared_ptr< ::openni2_tracker::TrackerUserArray > TrackerUserArrayPtr;
typedef boost::shared_ptr< ::openni2_tracker::TrackerUserArray const> TrackerUserArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openni2_tracker::TrackerUserArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openni2_tracker::TrackerUserArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace openni2_tracker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'openni2_tracker': ['/home/zheng/robot_ws_zheng/src/openni2_tracker/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::openni2_tracker::TrackerUserArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openni2_tracker::TrackerUserArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openni2_tracker::TrackerUserArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openni2_tracker::TrackerUserArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openni2_tracker::TrackerUserArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openni2_tracker::TrackerUserArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openni2_tracker::TrackerUserArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "825d95b7c6acaad9dc439d2148963f2e";
  }

  static const char* value(const ::openni2_tracker::TrackerUserArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x825d95b7c6acaad9ULL;
  static const uint64_t static_value2 = 0xdc439d2148963f2eULL;
};

template<class ContainerAllocator>
struct DataType< ::openni2_tracker::TrackerUserArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openni2_tracker/TrackerUserArray";
  }

  static const char* value(const ::openni2_tracker::TrackerUserArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openni2_tracker::TrackerUserArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# TrackerUserArray: This message contains a vector of openni2_tracker/TrackerUser messages.\n"
"openni2_tracker/TrackerUser[] users\n"
"int8 numUsers\n"
"\n"
"================================================================================\n"
"MSG: openni2_tracker/TrackerUser\n"
"# TrackerUser: Contains a snapshot of a single users tracking data. an ID, a vector of frames corresponding to each joint, a vector of confidences corresponding to each joint, and a vector of geometry_msgs/Transform messages corresponding to each joint. \n"
"Header header\n"
"uint8 uid\n"
"string tracker_id\n"
"string[] frames\n"
"float64[] confs\n"
"geometry_msgs/Transform[] transforms\n"
"geometry_msgs/Vector3[] projective\n"
"geometry_msgs/Vector3 center_of_mass\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::openni2_tracker::TrackerUserArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openni2_tracker::TrackerUserArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.users);
      stream.next(m.numUsers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackerUserArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openni2_tracker::TrackerUserArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openni2_tracker::TrackerUserArray_<ContainerAllocator>& v)
  {
    s << indent << "users[]" << std::endl;
    for (size_t i = 0; i < v.users.size(); ++i)
    {
      s << indent << "  users[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::openni2_tracker::TrackerUser_<ContainerAllocator> >::stream(s, indent + "    ", v.users[i]);
    }
    s << indent << "numUsers: ";
    Printer<int8_t>::stream(s, indent + "  ", v.numUsers);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENNI2_TRACKER_MESSAGE_TRACKERUSERARRAY_H
