ur5_r2:

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController

    publish_rate: 1000

  # Position Controllers ---------------------------------------
  shoulder_pan_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_pan_joint
    pid: {p: 10.0, i: 0.01, d: 1.0}
  shoulder_lift_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_lift_joint
    pid: {p: 10.0, i: 0.01, d: 1.0}
  elbow_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: elbow_joint
    pid: {p: 10.0, i: 0.01, d: 1.0}
  wrist_1_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist_1_joint
    pid: {p: 10.0, i: 0.01, d: 1.0}
  wrist_2_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist_2_joint
    pid: {p: 10.0, i: 0.01, d: 1.0}
  wrist_3_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist_3_joint
    pid: {p: 10.0, i: 0.01, d: 1.0}


/gazebo_ros_control:
  pid_gains:
    shoulder_pan_joint:
      p: 10.0
      i: 0.01
      d: 1.0
    shoulder_lift_joint:
      p: 10.0
      i: 0.01
      d: 1.0
    elbow_joint:
      p: 10.0
      i: 0.01
      d: 1.0
    wrist_1_joint:
      p: 10.0
      i: 0.01
      d: 1.0
    wrist_2_joint:
      p: 10.0
      i: 0.01
      d: 1.0
    wrist_3_joint:
      p: 10.0
      i: 0.01
      d: 1.0
