(cl:in-package rail_pose_estimation_msgs-msg)
(cl:export '(NECK_X-VAL
          NECK_X
          NECK_Y-VAL
          NECK_Y
          NOSE_X-VAL
          NOSE_X
          NOSE_Y-VAL
          NOSE_Y
          RIGHT_SHOULDER_X-VAL
          RIGHT_SHOULDER_X
          RIGHT_SHOULDER_Y-VAL
          RIGHT_SHOULDER_Y
          LEFT_SHOULDER_X-VAL
          LEFT_SHOULDER_X
          LEFT_SHOULDER_Y-VAL
          LEFT_SHOULDER_Y
          RIGHT_ELBOW_X-VAL
          RIGHT_ELBOW_X
          RIGHT_ELBOW_Y-VAL
          RIGHT_ELBOW_Y
          LEFT_ELBOW_X-VAL
          LEFT_ELBOW_X
          LEFT_ELBOW_Y-VAL
          LEFT_ELBOW_Y
          RIGHT_WRIST_X-VAL
          RIGHT_WRIST_X
          RIGHT_WRIST_Y-VAL
          RIGHT_WRIST_Y
          LEFT_WRIST_X-VAL
          LEFT_WRIST_X
          LEFT_WRIST_Y-VAL
          LEFT_WRIST_Y
          RIGHT_HIP_X-VAL
          RIGHT_HIP_X
          RIGHT_HIP_Y-VAL
          RIGHT_HIP_Y
          LEFT_HIP_X-VAL
          LEFT_HIP_X
          LEFT_HIP_Y-VAL
          LEFT_HIP_Y
          RIGHT_KNEE_X-VAL
          RIGHT_KNEE_X
          RIGHT_KNEE_Y-VAL
          RIGHT_KNEE_Y
          LEFT_KNEE_X-VAL
          LEFT_KNEE_X
          LEFT_KNEE_Y-VAL
          LEFT_KNEE_Y
          RIGHT_ANKLE_X-VAL
          RIGHT_ANKLE_X
          RIGHT_ANKLE_Y-VAL
          RIGHT_ANKLE_Y
          LEFT_ANKLE_X-VAL
          LEFT_ANKLE_X
          LEFT_ANKLE_Y-VAL
          LEFT_ANKLE_Y
          RIGHT_EYE_X-VAL
          RIGHT_EYE_X
          RIGHT_EYE_Y-VAL
          RIGHT_EYE_Y
          LEFT_EYE_X-VAL
          LEFT_EYE_X
          LEFT_EYE_Y-VAL
          LEFT_EYE_Y
          RIGHT_EAR_X-VAL
          RIGHT_EAR_X
          RIGHT_EAR_Y-VAL
          RIGHT_EAR_Y
          LEFT_EAR_X-VAL
          LEFT_EAR_X
          LEFT_EAR_Y-VAL
          LEFT_EAR_Y
))