// Generated by gencpp from file human_moveit_config/GetHumanIK.msg
// DO NOT EDIT!


#ifndef HUMAN_MOVEIT_CONFIG_MESSAGE_GETHUMANIK_H
#define HUMAN_MOVEIT_CONFIG_MESSAGE_GETHUMANIK_H

#include <ros/service_traits.h>


#include <human_moveit_config/GetHumanIKRequest.h>
#include <human_moveit_config/GetHumanIKResponse.h>


namespace human_moveit_config
{

struct GetHumanIK
{

typedef GetHumanIKRequest Request;
typedef GetHumanIKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetHumanIK
} // namespace human_moveit_config


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::human_moveit_config::GetHumanIK > {
  static const char* value()
  {
    return "2602509d5e7f9ded6d3747732576ab30";
  }

  static const char* value(const ::human_moveit_config::GetHumanIK&) { return value(); }
};

template<>
struct DataType< ::human_moveit_config::GetHumanIK > {
  static const char* value()
  {
    return "human_moveit_config/GetHumanIK";
  }

  static const char* value(const ::human_moveit_config::GetHumanIK&) { return value(); }
};


// service_traits::MD5Sum< ::human_moveit_config::GetHumanIKRequest> should match 
// service_traits::MD5Sum< ::human_moveit_config::GetHumanIK > 
template<>
struct MD5Sum< ::human_moveit_config::GetHumanIKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::human_moveit_config::GetHumanIK >::value();
  }
  static const char* value(const ::human_moveit_config::GetHumanIKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::human_moveit_config::GetHumanIKRequest> should match 
// service_traits::DataType< ::human_moveit_config::GetHumanIK > 
template<>
struct DataType< ::human_moveit_config::GetHumanIKRequest>
{
  static const char* value()
  {
    return DataType< ::human_moveit_config::GetHumanIK >::value();
  }
  static const char* value(const ::human_moveit_config::GetHumanIKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::human_moveit_config::GetHumanIKResponse> should match 
// service_traits::MD5Sum< ::human_moveit_config::GetHumanIK > 
template<>
struct MD5Sum< ::human_moveit_config::GetHumanIKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::human_moveit_config::GetHumanIK >::value();
  }
  static const char* value(const ::human_moveit_config::GetHumanIKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::human_moveit_config::GetHumanIKResponse> should match 
// service_traits::DataType< ::human_moveit_config::GetHumanIK > 
template<>
struct DataType< ::human_moveit_config::GetHumanIKResponse>
{
  static const char* value()
  {
    return DataType< ::human_moveit_config::GetHumanIK >::value();
  }
  static const char* value(const ::human_moveit_config::GetHumanIKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HUMAN_MOVEIT_CONFIG_MESSAGE_GETHUMANIK_H
