human:

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController

    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint_chest_z_controller:
    type: position_controllers/JointPositionController
    joint: joint_chest_z
    pid: {p: 450., i: 0.0, d: 20.}
  joint_chest_y_controller:
    type: position_controllers/JointPositionController
    joint: joint_chest_y
    pid: {p: 450.0, i: 0.0, d: 20.}
  joint1_controller:
    type: position_controllers/JointPositionController
    joint: joint1
    pid: {p: 450.0, i: 0.0, d: 20.0}
  joint2_controller:
    type: position_controllers/JointPositionController
    joint: joint2
    pid: {p: 450.0, i: 0, d: 20.0}
  joint3_controller:
    type: position_controllers/JointPositionController
    joint: joint3
    pid: {p: 80.0, i: 0.0, d: 1.5.0}

  joint5_controller:
    type: position_controllers/JointPositionController
    joint: joint5
    pid: {p: 450.0, i: 0.0, d: 20.0}
  joint6_controller:
    type: position_controllers/JointPositionController
    joint: joint6
    pid: {p: 450.0, i: 0, d: 20.0}
  joint7_controller:
    type: position_controllers/JointPositionController
    joint: joint7
    pid: {p: 80.0, i: 0.0, d: 1.5.0}

/gazebo_ros_control:
  pid_gains:
    joint_chest_z: {p: 450.0, i: 0.0, d: 20.0}
    joint_chest_y: {p: 450.0, i: 0.0, d: 20.0}
    joint1: {p: 450.0, i: 0.0, d: 20.0}
    joint2: {p: 450.0, i: 0.0, d: 20.0}
    joint3: {p: 80.0, i: 0.0, d: 1.5.0}
    joint5: {p: 450.0, i: 0.0, d: 20.0}
    joint6: {p: 450.0, i: 0.0, d: 20.0}
    joint7: {p: 80.0, i: 0.0, d: 1.5.0}
