# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from openpose_ros_msgs/PersonDetection.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import openpose_ros_msgs.msg

class PersonDetection(genpy.Message):
  _md5sum = "5cf57469f872bf144c62ed7904d5c159"
  _type = "openpose_ros_msgs/PersonDetection"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """BodyPartDetection[] face_landmark
BodyPartDetection[] body_part

================================================================================
MSG: openpose_ros_msgs/BodyPartDetection
uint32 part_id
uint32 x
uint32 y
float32 confidence
"""
  __slots__ = ['face_landmark','body_part']
  _slot_types = ['openpose_ros_msgs/BodyPartDetection[]','openpose_ros_msgs/BodyPartDetection[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       face_landmark,body_part

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PersonDetection, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.face_landmark is None:
        self.face_landmark = []
      if self.body_part is None:
        self.body_part = []
    else:
      self.face_landmark = []
      self.body_part = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.face_landmark)
      buff.write(_struct_I.pack(length))
      for val1 in self.face_landmark:
        _x = val1
        buff.write(_get_struct_3If().pack(_x.part_id, _x.x, _x.y, _x.confidence))
      length = len(self.body_part)
      buff.write(_struct_I.pack(length))
      for val1 in self.body_part:
        _x = val1
        buff.write(_get_struct_3If().pack(_x.part_id, _x.x, _x.y, _x.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.face_landmark is None:
        self.face_landmark = None
      if self.body_part is None:
        self.body_part = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.face_landmark = []
      for i in range(0, length):
        val1 = openpose_ros_msgs.msg.BodyPartDetection()
        _x = val1
        start = end
        end += 16
        (_x.part_id, _x.x, _x.y, _x.confidence,) = _get_struct_3If().unpack(str[start:end])
        self.face_landmark.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.body_part = []
      for i in range(0, length):
        val1 = openpose_ros_msgs.msg.BodyPartDetection()
        _x = val1
        start = end
        end += 16
        (_x.part_id, _x.x, _x.y, _x.confidence,) = _get_struct_3If().unpack(str[start:end])
        self.body_part.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.face_landmark)
      buff.write(_struct_I.pack(length))
      for val1 in self.face_landmark:
        _x = val1
        buff.write(_get_struct_3If().pack(_x.part_id, _x.x, _x.y, _x.confidence))
      length = len(self.body_part)
      buff.write(_struct_I.pack(length))
      for val1 in self.body_part:
        _x = val1
        buff.write(_get_struct_3If().pack(_x.part_id, _x.x, _x.y, _x.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.face_landmark is None:
        self.face_landmark = None
      if self.body_part is None:
        self.body_part = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.face_landmark = []
      for i in range(0, length):
        val1 = openpose_ros_msgs.msg.BodyPartDetection()
        _x = val1
        start = end
        end += 16
        (_x.part_id, _x.x, _x.y, _x.confidence,) = _get_struct_3If().unpack(str[start:end])
        self.face_landmark.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.body_part = []
      for i in range(0, length):
        val1 = openpose_ros_msgs.msg.BodyPartDetection()
        _x = val1
        start = end
        end += 16
        (_x.part_id, _x.x, _x.y, _x.confidence,) = _get_struct_3If().unpack(str[start:end])
        self.body_part.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3If = None
def _get_struct_3If():
    global _struct_3If
    if _struct_3If is None:
        _struct_3If = struct.Struct("<3If")
    return _struct_3If
